services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: oauth_example
      POSTGRES_USER: oauth
      POSTGRES_PASSWORD: secret
      TZ: UTC
      PGTZ: UTC
    ports:
      - 8888:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
